name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mrdomino/setup-cosmocc@v1
        with:
          version: 4.0.2
      - uses: actions/checkout@v4
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: bbazelisk
          path: bbazelisk
